name: avispets
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'



# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  page_view_dot_indicator: ^2.3.0
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.17
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  go_router: ^14.6.0
  intl: ^0.19.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  video_player: ^2.9.2
  camera: ^0.11.0+2
  video_editor: ^3.0.0
  file_picker: ^8.1.4
  app_settings: ^5.1.1
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  flutter_timezone: ^3.0.1
  geolocator: ^13.0.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  firebase_crashlytics: ^4.1.5
  country_code_picker: ^3.1.0
  get: ^4.6.6
  share_plus: ^10.1.2
  flutter_html: ^3.0.0-beta.2
  emoji_picker_flutter: ^3.1.0
  cached_network_image: ^3.4.1
  giphy_get: ^3.5.6
  pinch_zoom_release_unzoom: ^1.0.3
  socket_io_client: ^3.0.2
  pin_code_fields: ^8.0.1
  blinking_text: ^1.0.4
  equatable: ^2.0.5
  dio: ^5.7.0
  http: ^1.2.2
  google_sign_in: ^6.2.2
  flutter_quill: ^10.8.5
  vsc_quill_delta_to_html: ^1.0.5
  flutter_gcaptcha_v3: ^2.1.1
  flutter_facebook_auth: ^7.1.1
  flutter_local_notifications: ^18.0.1
  readmore: ^3.0.0
  package_info_plus: ^8.1.1
  version: ^3.0.2
  flutter_otp_text_field: ^1.2.0
  dotted_line: ^3.2.3
  flutter_image_compress: ^2.3.0
  video_compress: ^3.1.3
  flutter_plugin_android_lifecycle: ^2.0.23
  appinio_video_player: ^1.2.2
  ffmpeg_kit_flutter: ^6.0.3
  mapbox_gl: ^0.16.0
  flutter_branch_sdk: ^8.1.1
  video_thumbnail: ^0.5.2
  geocoding: ^3.0.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  custom_info_window: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: true
  ios: true
  #  image_path: "assets/images/onboard/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboard/
    - assets/images/markers/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/animations/
    - assets/raw/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

fonts:
  - family: poppins_bold
    fonts:
      - asset: assets/fonts/Poppins_Bold.ttf
        weight: 900
  - family: poppins_medium
    fonts:
      - asset: assets/fonts/Poppins_Medium.ttf
  - family: poppins_regular
    fonts:
      - asset: assets/fonts/Poppins_Regular.ttf
  - family: poppins_italic
    fonts:
      - asset: assets/fonts/Poppins_Italic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages