require('dotenv').config();
var express = require('express');
var path = require('path');
var bodyParser = require('body-parser');
var fileUpload = require('express-fileupload');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var expressValidator = require('express-validator');
var cors = require('cors');
var i18n = require("i18n");
var fs = require("fs");
var https = require("https");
