import 'package:get/get.dart';

class Lang extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English
        'en_en': {
          'YourNewsFeed': 'Your News Feed',
          'centerElseWhere': 'Center Elsewhere',
          'useCurrLoc': 'Use your current location',
          'Animalerie': 'Petstore',
          'Bars': 'Bars',
          'coffee': 'coffee',
          'Evenement': 'Events',
          'Exposition': 'Exposition',
          'Hotel': 'Hotel',
          'localisation': 'localisation',
          'Parks': 'Parks',
          'Restaurants': 'Restaurants',
          'supermarket': 'supermarket',
          'Toilettage': 'Toilettage',
          'Veterinaire': 'Veterinaire',

          'aroundYou': 'Around You',
          'applyfilters': 'Apply Filters',
          'filter': 'Filters',
          'useLoc': 'Use Location',
          'useMap': 'Use Map',

          'explore': 'Explore',
          'creategroup': 'Create a discussion',
          'signupfb': 'Sign up with Facebook',
          'signupgg': 'Sign up with Google',
          'signupapp': 'Sign up with Apple',
          'signinfb': 'Login with Facebook',
          'signingg': 'Login with Google',
          'signinapp': 'Login with Apple',
          'email': 'name@gmail.com',
          'enterOtp': 'Please enter your otp',
          'otpInvalid': 'Invalid Otp',
          'enterReferral': 'Please enter referral code',
          'resend': 'Resend',
          'inviteFriends': 'Invite Friends',
          'invite': 'Invite',
          'copyYourCode': 'Copy your code',
          'rankingDec':
              'The ranking is updated every week, on Sunday at midnight.',
          'leaderboard': 'Leaderboard',
          'weekly': 'Weekly',
          'name1': 'Name',
          'remaining': 'Remaining',
          'published': 'Published',
          'earnWithPerform': 'Earn points when you perform',
          'gameInfoTitle': 'Earn points by helping to power AvisPets App!',
          'gameInfoDec':
              'With our app, every contribution earns you points. The more you interact, the more you are rewarded with exclusive benefits. Share your experiences, discover new products, and accumulate points at every step!',
          'female': 'Female',
          'male': 'Male',
          'pointsHistory': 'Point History',
          'totalBadges': 'You have earned',
          'moreLevels': 'More Levels',
          'noEarnHistory': 'No earned point history',
          'earn': 'Earn another',
          'toUpgrade': 'PTS to reach the next level',
          'level': 'Levels',
          'ranking': 'Ranking',
          'badgesObtained': 'Badges obtained',
          'badges': ', for the moment',
          'badge': 'badge',
          'badgesTitle': 'Badges',
          'allBadges': 'All Badges',
          'earnMore': 'The points table',
          'scoredPoints': 'Points Earned',
          'verification': 'Verification',
          'statistics': 'Statistics',
          'viewAll': 'View All',
          'view': 'View Post',
          'sendTo': 'Send To',
          'rememberSpam':
              'Enter it below to confirm your identity and the Avispets app. It will only take a moment!',
          'moreChoices': 'More Choices',
          'otpNote': "Note: Don't forget to check your junk/SPAM messages",
          'sendDes': 'Select the friends with whom you want to share this post',
          'notReceived': 'This code will expire in 2 minute. Need a new code?',
          'otpDec':
              'We just sent you a 6-digit verification code to your email',
          'otpDec2':
              'We Will send you a one time password on this mobile Number',
          'otp2': 'Send Code via phone number? ',
          'otp3': 'Send Code to email? ',
          'update': 'Update Avispets?',
          'updateBtn': 'Update',
          'updateDes':
              'Avispets recommends that you update the app to the latest version',
          'selectStar': 'Please select atleast one star from every question',
          'password': '******',
          'phone': '123 456 7890',
          'city': 'City',
          'address': 'Area',
          'add': 'Add',
          'password2': 'Password',
          'forgotPassword': 'Forgot',
          'forgotPassword2': 'Password',
          'verify': 'Verify',
          'close': 'Close',
          'orContinueWith': 'OR',
          'haveAnAccount': 'Don’t have an account? ',
          'editAnimalPhoto': 'Edit animal photo',
          'animalPhoto': 'Edit photo',
          'animalPhotoCreate': 'Add a photo of your pet',
          'bio': 'Bio',
          'enterBio': 'Enter your bio',
          'enterBioP':
              'Go to the “Edit my profile” section to complete your bio',
          'purchasePlace': 'Place of purchase',
          'changeProfilePhoto': 'Change my profile picture',
          'createAccount': 'Create New Account',
          'help': 'Help',
          'login': 'Lets Sign You In',
          'loginbtn': 'Login',

          'enterLoginDetail': 'Please enter your details to log in.',
          'createAccountDetails': 'Create your account and explore AvisPets',
          'chooseYourLanguage': 'Choose Your Language',
          'forgotPasswordDesc':
              'Enter the email address with your account and we\'ll send an email with confirmation to reset your password.',
          'resetPassword': 'Reset Password',
          'accountCreate': 'Create Account',
          'firstName': 'First Name',
          'lastName': 'Last Name',
          'confirmPassword': 'Confirm Password',
          'pseudo': 'Pseudo',
          'referCode': 'Referral code',
          'iAgreeTo': 'I agree to',
          'termsAndConditions': 'terms and conditions',
          'termsAndConditions1': 'Terms & Conditions',
          'privacy': 'privacy policy.',
          'privacy1': 'Privacy Policy',
          'haveAnAccount1': 'Have an account? ',
          'next': "Next",
          'getStarted': "Get Started",
          'dog': 'Dog',
          'dogFeeds': 'Dog Feeds',
          'catFeeds': 'Cat Feeds',
          'cat': 'Cat',
          'noAnimals': 'No Animal',
          'postQuestion1': 'Start a discussion',
          'later': 'Skip',
          'desc1': 'Do You Have Pets In Your Home?',
          'desc2':
              'By providing information about your pet, you allow us to offer you personalized content.',

          'myAnimals': 'My Animals',
          'skip': 'Skip',

          'myAnimals1': 'My-Animals',
          'allTopic': 'All Topics',
          'reviewSubmitted': 'Review\nsubmitted',
          'questionsSubmitted': 'Question(s)\nsubmitted',
          'postsSubmitted': 'Discussion(s)\nlaunched',
          'responsesSubmitted': 'Response(s)\nsubmitted',
          'chooseMembers': 'Choose member(s)',
          'cropImage': 'Crop Image',
          'friends': 'Add Friends',
          'following': 'Following',
          'followers': 'Follower',
          'newGroup': 'New chat group',
          'groupName': 'Group\'s Name',
          'notifications': 'Notifications',
          'myProfile': 'My Profile',
          'myActivities': 'My Activities',
          'editProfile': 'Edit Profile',
          'editText': 'Edit Text',
          'myAccount': 'Account',
          'forums': 'Forums',
          'myThread': 'My Threads',
          'changePassword': 'Change Password',
          'faqs': 'FAQs',
          'contactUs': 'Contact Us',
          'changeLanguage': 'Change Language',
          'deactivateAccount': 'Deactivate Account',
          'deleteAccount': 'Delete Account',
          'receiveNotification':
              'I would like to receive email notifications when comments are received on my post',
          'yourMessage': 'Your Message',
          'chats': 'Chats',
          'chat': 'Chat',
          'addAnimal': 'Add an animal',
          'edit': 'Edit',
          'nameAnimal': 'Name',
          'species': 'Species',
          'species1': 'Species: ',
          'dob': 'Date of birth',
          'dontKnowDOB': 'I don\'t know his date of birth',
          'send': 'Send',
          'race': 'Breed',
          'DonotKnowBreed': 'I don\'t know the breed',
          'gender': 'Gender',
          'sterilized': 'Sterilized*',
          'photo': 'Upload Photos',
          'anotherAnimal': 'I have another animal',
          "addAPost": "Add A Post",
          "byName": "By Name",
          "byAddress": "By Address",
          "url": "URL",
          "createANewPlace": "Create A New Place",
          "evaluateService": "Evaluate the quality of service",
          "atmosphere": "Atmosphere And Environment",
          "safety": "Safety For Animals",
          "accessibility": "Accessibility And Infrastructure?",
          "socialInteractions": "Social Interactions",
          "addPhotos": "Add Photos For You And Your Followers",
          "publish": "Publish",
          'addPostTitle': 'Add Post',
          'post': 'Post',
          'sharePost': 'Share post',
          'choosePicture': 'Choose Picture',
          'cameraGallery': 'Post a Photo/Video',
          'cameraGallery1': 'Add A Post',
          'chatMedia': 'Select the document',

          'topic': 'Topics',
          'favorites': 'Favorites',
          'questionsAsked': 'Questions asked',
          'publishedPosts': 'Published posts',
          'chooseVideo': 'Choose Video',
          'postQuestion': 'Post a Question',
          'question': 'Question',
          'answer': 'Answer',
          'chooseFiletype': 'Choose a filetype',
          'camera': 'Camera',
          'phoneLibrary': 'Phone Library',
          'attachments': 'Attachment',

          'selectTermsPrivacy': 'Please select agree terms and conditions',
          'addComment': 'comment....',
          'replyBy': 'Reply by',
          'speciesName': 'Species \'s Name',
          'animalName1': 'Animal\'s Name',
          'atLeastOneCategory': 'Select atleast  1 Category',
          'atLeastOneUser': 'Select atleast  1 User',
          'selectPhotoVideo': 'Select Photo & Video*',
          'selectCategory': 'Select Category',
          'category': 'Category',
          'selectSubCategory': 'Select Sub Category',
          'description': 'Description*',
          'question1':
              'What do you think are the strong points of the product?',
          'question2': 'What do you think are the weak points of the product?',
          'savePost': 'Publish',
          'name': 'Name: ',
          'type': 'Type',
          'DOB': 'DOB: ',

          'gender:': 'Gender: ',
          'gender1': 'Gender',
          'logout': 'Logout',
          'home': 'Home',
          'postDetails': 'Post details',
          'questionDetails': 'Question details',
          'yes': 'Yes',
          'no': 'No',
          'subject': 'Subject',
          'message': 'Message',
          'submit': 'Submit',
          'updateAnimal': 'Update Animal',
          'oldPassword': 'Old Password',
          'newPassword': 'New Password',
          'updatePassword': 'Update Password',
          'save': 'Save',
          'headingSelectAnimal': 'Select Animal',
          'noAnimalCreate': 'Please add an animal to be able to post a post',
          'review': 'Review',
          'comment': 'Comments',
          'reply': 'Reply',
          'replies': 'Replies',
          'myReply': 'My Answers',
          'delete': 'Delete',
          'success': 'Success!',
          'done': 'Done',
          'reportPost': 'Report Post',
          'yourNewsFeed': 'Your News Feeds',
          'recentFeed': 'Recent Feeds',
          'clearConversation': 'Clear Conversation',
          'noConversation': 'No Conversation',
          'clearConversationDesc':
              'Are you sure you want to clear conversation?',
          'deleteChat': 'Clear Chat',
          'deleteChatDesc': 'Are you sure you want to clear the discussion?',
          'groupAdmin': 'Group Admin',
          'ExitGroup': 'Exit Group',
          'blockUser': 'Block User',
          'unblockUser': 'unblock User',
          'blockUserDesc': 'Are you sure you want to block user?',
          'unblockUserDesc': 'Are you sure you want to unblock user?',
          'allFeeds': 'All Feeds',
          'myFeed': 'My Feeds',
          'favFeeds': 'Fav Feeds',
          'yourNewsFeed1': 'My Activities',
          'yourNewsFeed2': 'Your Favorites Feeds',
          'pickAnOption': 'Pick an option',
          'writeReview': 'Description',
          'follow': 'Follow',
          'unfollow': 'Unfollow',
          'search': 'Search...',
          'addMembers': 'Add Members',
          'members1': 'Members',
          'deleteAnimal': 'Delete Animal',
          'myFollowers': 'My Followers',
          'brand': 'Brand',
          'fullNameProduct': 'Full Name of Product',
          'packaging': 'Packaging (weight, size, etc.)',
          'weight': 'Weight',

          'members': 'members',
          'member': 'member',
          'areRemove': 'Are you sure you want to leave the group?',
          'from': 'from',
          'group': 'Group',
          'groupInfo': 'Group Info',
          'changeGroupName': 'Change group name',
          'enterMessage': 'Please enter the message',
          'enterGroupName': 'Please enter group name',
          'enterDescription': 'Please enter the description',
          'enterTitle': 'Please enter the title',
          'enterBrand': 'Please enter the brand',
          'enterProductName': 'Please enter the product name',
          'enterPackage': 'Please enter the product weight',
          'offline': 'Offline',
          'online': 'Online',
          'enterSubject': 'Please enter the subject',
          'selectAnyOption': 'Please select any option',
          'noDataFound': 'No Data Found',
          'noComments': 'No Comments',
          'noNotification': 'No Notifications',
          'noReply': 'No Reply',
          'noReplies': 'No Replies',

          'noFriends': 'No Friends',
          'noFollower': 'No Followers',
          'noAnimal': 'No Animals',
          'itching': 'Itching - Hair loss',
          'lowIrritation': 'Low irritation - Dull hair',
          'everythingIsFine': 'Everything is fine - silky bristles',
          'doesLike': 'Doesn\'t Like',
          'like': 'Like',
          'likes': 'Likes',
          'wantsMore': 'Wants More',
          'abnormalPoops': 'Abnormal poops',
          'stomach pain or gas': 'stomach pain or gas',
          'everythingFine': 'Everything is fine',
          'selectAnimal': 'Select ',
          'selectCategory1': 'Please enter the subject',
          'selectSubCategory1': 'Please enter the subject',
          'areYouSure': 'Are You sure?',
          'areYouSureDesc': 'Do you want to exit from the App',

          //createPost
          'skin': 'Skin',
          'appetite': 'Appetite',
          'digestion': 'Digestion',
          'price': 'Price',
          'paid': 'paid',
          'numEnter': 'number enter',
          'star1': 'Not at all appetizing (it rejects the food visually)',
          'star2': 'Not appetizing (it refuses to eat)',
          'star3': 'Moderately appetizing (it eats but does not finish)',
          'star4': 'Rather appetizing (it likes the food)',
          'star5': 'Extremely appetizing (it loves it)',

          // reportList
          'doNotLike': 'I just don’t like it',
          'spam': 'It’s spam',
          'nudity': 'Nudity or sexual activity',
          'hateSpeech': 'Hate speech or symbols',
          'falseInfo': 'False information',
          'viewReply': 'Replies',
          'remove': 'Remove',
          'clearFilter': 'Clear Filters',

          'deleteReveicer': 'This post was deleted',
          'deleteSender': 'You deleted this post',

          //createAnimal
          'animalName': 'Please enter the pet name',
          'animalWeight': 'Please enter the animal weight',
          'animalType': 'Please enter the pet type',
          'animalType1': 'Please select the pet',
          'animalRace': 'Please enter pet species',
          'animalbreed': 'Please enter the pet species',
          'animalDob': 'Please enter the Dob',
          'animalGender': 'Please enter the gender',
          'animalAge': 'Please enter the age',

          'animalSterilized': 'Please enter the Sterilized',
          'animalImage': 'Please upload pet\'s image',

          //friendScreen
          'showMore': 'Home - Forums',
          'showLess': 'show less',
          'suggestions': 'Suggestions',
          'suggestedForums': 'Forums 🐶🐱',
          'blockedContact': 'You blocked this contact. Tap to unblock',

          //dialogs(success)
          'deleteComment': 'Your comment have been delete.',
          'deleteReply': 'Your reply have been delete.',

          'deletePost': 'Your post have been delete.',
          'report': 'Post reported successfully.',
          'animal': 'Your animal have been saved.',

          //dialogs
          'dialogCommentTitle': 'Delete comment',
          'dialogComment': 'Are you sure you want to delete comment?',

          'dialogReplyTitle': 'Delete reply',
          'dialogReply': 'Are you sure you want to delete reply?',

          'dialogQuestionTitle': 'Delete discussion',
          'dialogQuestion': 'Are you sure you want to delete the discussion?',

          'dialogAnimalDesc': 'Are you sure you want to delete this Animal?',
          'dialogPostTitle': 'Delete Post',
          'dialogPost': 'Are you sure you want to delete post?',
          'logoutDesc': 'Are you sure you want to log out?',
          'title': 'Title',
          'deactivateAccountDesc':
              'Do you really want to deactivate this account?',
          'deleteAccountDesc': 'Do you really want to delete this account?',

          //toaster
          'enterEmail': 'Please enter the email',
          'enterPhone': 'Please enter the phone number',
          'enterAddress': 'Please enter the address',
          'enterCity': 'Please enter the address',
          'validEmail': 'Please enter your valid  email',
          'enterPassword': 'Please enter the valid password',
          'currentPassword': 'Please enter the Current password',
          'enterPassword1': 'Please enter the password',
          'passwordLength': 'Password must be at least 6 character',
          'enterConfirmPassword': 'Please enter the confirm password',
          'notMatch': 'Password and Confirm-password are not same',
          'enterFirstName': 'Please enter the first name',
          'enterLastName': 'Please enter the last name',
          'enterDepartment': 'Please enter your department',
          'enterPseudo': 'Please enter the pseudo',

          //notification
          'sendYouMess': 'sent a message',
          'hasCommented': 'commented on a post',
          'hasReplies': 'replied on your comment',
          'hasRepliesTopic': 'commented on your topic',
          'likeTopic': 'your topic reply',
          'startFollow': 'started following you',
          'feedLike': 'liked a post.',

          'year': 'year',
          'years': 'years',
          'month': 'month',
          'months': 'months',
          'week': 'week',
          'weeks': 'weeks',
          'day': 'day',
          'days': 'days',
          'hour': 'hour',
          'hrs': 'hrs',
          'min': 'min',
          'justNow': 'right now',
          'ago': 'ago',

          'groupCreated': 'Group Created',
          'removed': 'Removed',
          'left': 'Left',
          'newMember': 'New Member Added ',
          'addGroupPhoto': 'Add a group photo',
          'editGroupPhoto': 'Replace a group photo',
          'more': 'See More',
          'addAnother': 'Add more',
          'maxPhotos': 'You can select maximum of 2 images',
          'select2PhotoTitle': 'Add up to 2 photos:',
          'select2PhotoTitle1': '• one of the product tested',
          'select2PhotoTitle2': '• one of your pet with the product',
          'passcode': 'Passcode',
        },

        // French
        'fr_fr': {
          'YourNewsFeed': 'Your News Feed',
          'useCurrLoc': 'Utiliser votre localisation actuelle',
          'centerElseWhere': 'Center Elsewhere',
          'simulateLoc': 'Simulate A Location',
          'Animalerie': 'Animalerie',
          'Bars': 'Bars',
          'coffee': 'coffee',
          'Evenement': 'Evenements',
          'Exposition': 'Exposition',
          'Hotel': 'Hotel',
          'localisation': 'localisation',
          'Parks': 'Parks',
          'add': 'Add',
          'Restaurants': 'Restaurants',
          'supermarket': 'supermarket',
          'Toilettage': 'Toilettage',
          'Veterinaire': 'Veterinaire',
          'aroundYou': 'A proximité de vous',
          'useLoc': 'Utiliser Localisation',
          'useMap': 'Utiliser la carte',
          'applyfilters': 'Appliquer les filters',
          'filter': 'Filtres',
          'weight': 'Poids',
          'verify': 'Verifier',
          'signupfb': 'S\'inscrire avec Facebook',
          'signupgg': 'S\'inscrire avec Google',
          'signupapp': 'S\'inscrire avec Apple',
          'signinfb': 'Se connecter avec Facebook',
          'signingg': 'Se connecter avec Google',
          'signinapp': 'Se connecter avec Apple',
          'email': 'nom@gmail.com',
          'verification': 'Vérification',
          'statistics': 'Statistiques',
          'viewAll': 'Tout afficher',
          'view': 'Voir l\'article',
          'sendTo': 'Envoyer à',
          'rememberSpam':
              'Entrez-le ci-dessous pour confirmer votre identité et l’application Avispets. Cela ne prendra qu’un instant!',
          'moreChoices': 'Plus de choix',
          'otpNote':
              "Remarque : N'oubliez pas de vérifier vos messages indésirables/SPAM",
          'sendDes':
              'Sélectionnez les amis avec qui vous souhaitez partager cette publication',
          'resend': 'Renvoyer',
          'inviteFriends': 'Inviter des amis',
          'invite': 'Inviter',
          'copyYourCode': 'Copiez votre code',
          'rankingDec':
              'Le classement est mis à jour chaque semaine, le dimanche à minuit.',
          'leaderboard': 'Classement',
          'weekly': 'Hebdomadaire',
          'remaining': 'Restant',
          'published': 'Publié',
          'earnWithPerform': 'Gagnez des points lorsque vous effectuez',
          'gameInfoTitle':
              'Gagnez des points en contribuant à alimenter AvisPets App !',
          'gameInfoDec':
              'Avec notre application, chaque contribution vous rapporte des points. Plus vous interagissez, plus vous êtes récompensé avec des avantages exclusifs. Partagez vos expériences, découvrez de nouveaux produits, et accumulez des points à chaque étape !',
          'male': 'Mâle',
          'pointsHistory': 'Historique des points',
          'totalBadges': 'Vous avez gagné',
          'moreLevels': 'Plus de niveaux',
          'noEarnHistory': 'Aucun historique de points gagnés',
          'female': 'Femelle',
          'level': 'Niveaux',
          'ranking': 'Classement',
          'badgesObtained': 'Insignes obtenus',
          'allBadges': 'Tous les badges',
          'badges': ', pour le moment ',
          'badge': 'badge',
          'badgesTitle': 'Mes badges',
          'earn': 'Gagner encore',
          'toUpgrade': 'PTS pour atteindre le niveau supérieur',
          'earnMore': 'Le tableau des points ',
          'scoredPoints': 'Points Gagnés',
          'notReceived':
              "Ce code expirera dans 2 minute. Besoin d'un nouveau code ?",
          'otpInvalid': 'Otp invalide',
          'enterReferral': 'Veuillez entrer le code de parrainage',
          'enterOtp': 'Veuillez entrer votre OTP',
          'otpDec':
              'Nous venons de vous envoyer un code de vérification à 6 chiffres à votre adresse courriel',
          'otp2Dec':
              'Nous venons de vous envoyer un code de vérification à 6 chiffres à votre numéro de téléphone',
          'otpDec2':
          'Nous venons de vous envoyer un code de vérification à 6 chiffres à votre numéro de téléphone',
          'otp2': 'Vérifier avec un numéro de téléphone?',
          'otp3': 'Vérifier avec un votre email?',
          'update': 'Mise à jour Avispets?',
          'updateBtn': 'Mise à jour',
          'updateDes':
              "Avispets vous recommande de mettre à jour l'application vers la dernière version",
          'selectStar':
              'Veuillez sélectionner au moins une étoile pour chaque question',
          'password': '******',
          'password2': 'Mot de passe',
          'phone': '123 456 7890',
          'city': 'City',
          'address': 'Area',
          'forgotPassword': 'Vous avez oublié le ',
          'forgotPassword2': 'Mot de passe',
          'close': 'Fermer',
          'orContinueWith': 'Ou',
          'haveAnAccount': 'Vous n\'avez pas de compte? ',
          'editAnimalPhoto': 'Modifier la photo de l’ animal',
          'animalPhoto': 'Modifier la photo',
          'animalPhotoCreate': 'Ajoutez une photo de votre animal de compagnie',
          'bio': 'Biographie',
          'enterBio': 'Entrez votre bio',
          'enterBioP':
              'Rdv dans la section “Editer mon profil”, pour compléter votre bio',
          'purchasePlace': 'Nom du magasin / site internet',
          'changeProfilePhoto': 'Modifier ma photo de profil',
          'createAccount': 'Créer un compte',
          'help': 'Aide',
          'login': 'Se connecter',
          'loginbtn': 'Se connecter',
          'explore': 'Explorer',
          'enterLoginDetail':
              'Veuillez saisir vos coordonnées pour vous connecter.',
          'createAccountDetails': 'Créez votre compte et explorez AvisPets',
          'chooseYourLanguage': 'Choisissez votre langue',
          'forgotPasswordDesc':
              'Entrez l\'adresse e-mail de votre compte et nous vous enverrons un e-mail de confirmation pour réinitialiser votre mot de passe.',
          'resetPassword': 'Réinitialiser le mot de passe',
          'accountCreate': 'Créer un compte',
          'firstName': 'Prénom',
          'lastName': 'Nom de famille',
          'confirmPassword': 'Confirmez votre mot de passe',
          'pseudo': 'Pseudo',
          'referCode': 'Code de référence',
          'iAgreeTo': 'Je suis d\'accord pour',
          'termsAndConditions': 'Conditions d\'utilisation',
          'termsAndConditions1': 'Conditions d\'utilisation',
          'privacy': 'Politiques de confidentialité.',
          'privacy1': 'Politiques de confidentialité',
          'haveAnAccount1': 'Se créer un compte?',
          'next': "Suivant",
          'getStarted': "Commencer",
          'addAnother': 'Add more',
          'deleteReveicer': 'Ce message a été supprimé',
          'deleteSender': 'Vous avez supprimé ce message',
          'dog': 'Chien',
          'cat': 'Chat',
          'noAnimals': 'Aucun animal',
          'noAnimal': 'Pas d\'animaux',
          'later': 'Skip',
          'desc1': 'Avez-vous des animaux chez vous?',
          'desc2':
              'By providing information about your pet, you allow us to offer you personalized content.',
          'myAnimal': 'Mon animal',
          'myAnimals1': 'Mon animal ou Mes animaux',
          'friends': 'Ajouter des amis',
          'following': 'Suivi',
          'followers': 'Follower',
          'addComment': 'Commentaire...',
          'notifications': 'Notifications',
          'myProfile': 'Mon profil',
          'editProfile': 'Editer mon profil',
          'changePassword': 'Changer le mot de passe',
          'faqs': 'FAQ',
          'contactUs': 'Contactez-nous',
          'changeLanguage': 'Changer de langue',
          'deactivateAccount': 'Désactiver le compte',
          'review': 'Revoir',
          'logout': 'Se déconnecter',
          'comment': 'Commentaires',
          'yes': 'Oui',
          'no': 'Non',
          'subject': 'Objet',
          'message': 'Message',
          'submit': 'Soumettre',
          'save': 'Sauvegarder',
          'oldPassword': 'Ancien mot de passe',
          'newPassword': 'Nouveau mot de passe',
          'updatePassword': 'Mettre à jour le mot de passe',
          'headingSelectAnimal': 'Sélectionnez un animal',
          'reply': 'Réponse',
          'delete': 'Supprimer',
          'success': 'Succès!',
          'done': 'Fait',
          'reportPost': 'Signaler le message',
          'home': 'Accueil',
          'yourNewsFeed': 'Votre fil d’actualité',
          'pickAnOption': 'Choisissez une option',
          'writeReview': 'Ecrire une description',
          'postDetails': 'Détail du post',
          'follow': 'Suivre',
          'search': 'Recherche...',
          'name1': 'Nom',
          'addMembers': 'Ajouter des membres',
          'edit': 'Modifier',
          'myActivities': 'Mes activités',
          'selectAnyOption': 'Veuillez sélectionner une option',
          'addAnimal': 'Ajouter un animal',
          'nameAnimal': 'Nom',
          'species': 'Espèce',
          'species1': 'Race: ',
          'dob': 'Date de naissance',
          'dontKnowDOB': 'je ne connais pas sa date de naissance',
          'send': 'Envoyer',
          'race': 'Race',
          'Breed': 'Race',
          'DonotKnowBreed': 'je ne connais pas la race',
          'gender': 'Sexe',
          'gender1': 'Sexe',
          'sterilized': 'Stérilisé(e)*',
          'photo': 'Ajouter des photos',
          'anotherAnimal': 'J\'ai un autre animal',
          'unfollow': 'Ne plus suivre',
          'addPost': 'Publier un post',
          'addPostTitle': 'Ajoutez un avis',
          'choosePicture': 'Choisir une image',
          'chooseVideo': 'Choisissez la vidéo',
          'postQuestion': 'Publier une question',
          'postQuestion1': 'Lancer une discussion',
          'chooseFiletype': 'Choisissez un type de fichier',
          'camera': 'Appareil photo',
          'phoneLibrary': 'Galerie photos',
          'attachments': 'Pièce jointe ',

          'cameraGallery': 'Publier une photo/vidéo',
          'deleteAnimal': 'Supprimer un animal',
          'selectPhotoVideo': 'Sélectionnez une photo ou vidéo*',
          'selectCategory': 'Choisissez une catégorie ',
          'category': 'Catégorie',
          'selectSubCategory': 'Sélectionnez une sous-catégorie',
          'description': 'Description*',
          'question1': 'Selon vous, quels sont les points forts du produit?',
          'question2': 'Selon vous, quels sont les points faibles du produit?',
          'savePost': 'Publier',
          'myFollowers': 'Mes abonnés',
          'deleteAccount': 'Supprimer le compte',
          'name': 'Nom: ',
          'type': 'Type d’animal',
          'DOB': 'Date de naissance: ',
          'gender:': 'Sexe: ',
          'dialogAnimalDesc': 'Êtes-vous sûr de vouloir supprimer cet animal ?',
          'selectTermsPrivacy': 'Veuillez accepter nos conditions générales',
          'updateAnimal': 'Mettre à jour l\'animal',
          'speciesName': 'Nom de l\'espèce',
          'animalName1': 'Nom des animaux',
          'enterSubject': 'Veuillez entrer le sujet',
          'enterMessage': 'Veuillez saisir le message',
          'enterGroupName': 'Veuillez entrer le nom du groupe',
          'enterDescription': 'Veuillez entrer la description',
          'yourNewsFeed1': 'Mes activités',
          'yourNewsFeed2': 'Vos flux favoris',
          'question': 'Question',
          'answer': 'Réponse',
          'chats': 'Discussions',
          'allTopic': 'Tous les sujets',

          //createPost
          'qualityOfPoop': 'Qualité des selles',
          'appetite': 'Appétence',
          'digestion': 'Digestion',
          'price': 'Prix',
          'paid': 'payé',
          'numEnter': 'nombre entier',

          'star1':
              'Pas du tout appétissant (il rejette visuellement la nourriture)',
          'star2': 'Pas appétissant (il refuse de manger)',
          'star3': 'Moyennement appétissant (il en mange mais ne finit pas)',
          'star4': 'Plutôt appétissant (il aime la nourriture)',
          'star5': 'Extrêmement appétissant (il adore)',

          'viewReply': 'Réponses',
          'myReply': 'Mes réponses',
          'recentFeed': 'Flux récents',
          'noDataFound': 'Aucune donnée disponible',
          'noComments': 'Sans commentaires',
          'noReply': 'Pas de réponse',
          'noFriends': 'Pas d\'amis',
          'noFollower': 'Aucun abonné',
          'post': 'Publier',
          'sharePost': 'Post partagé',
          'enterTitle': 'Veuillez entrer le titre',
          'questionDetails': 'Détails des questions',
          'allFeeds': 'Actualités',
          'myFeed': 'Mes posts',
          'favFeeds': 'Mes favoris',
          'passwordLength':
              'Le mot de passe doit contenir au moins 6 caractères',
          'dogFeeds': 'Aliments pour chiens',
          'catFeeds': 'Aliments pour chats',
          'clearConversation': 'Supprimer les messages',
          'clearConversationDesc':
              'Êtes-vous sûr de vouloir effacer la conversation ?',
          'blockUser': 'Bloquer un utilisateur',
          'unblockUser': 'Débloquer l\'utilisateur',
          'deleteChatDesc':
              'Êtes-vous sûr de vouloir supprimer la discussion ?',
          'deleteChat': 'Supprimer la discussion',
          'myAccount': 'Compte',
          'blockUserDesc': 'Êtes-vous sûr de vouloir bloquer l\'utilisateur ?',
          'unblockUserDesc':
              'Êtes-vous sûr de vouloir débloquer l\'utilisateur ?',
          'yourMessage': 'Votre message',
          'chat': 'Chat',
          "addAPost": "Ajouter un poste",
          "byName": "Par Nom",
          "byAddress": "Par Adresse",
          "url": "URL (pour les magasins en ligne)",
          "createANewPlace": "Créer un nouvel endroit",
          "evaluateService": "Évaluez la qualité du service",
          "atmosphere": "Ambiance et environnement",
          "safety": "Sécurité pour les animaux",
          "accessibility": "Accessibilité et infrastructure?",
          "socialInteractions": "Interactions sociales",
          "addPhotos": "Ajoutez des photos pour vous et vos abonnés",
          "publish": "Publier",

          //createAnimal
          'animalName': 'Veuillez entrer le nom de l\'animal',
          'animalWeight': 'Veuillez entrer le poids de l\'animal',

          'animalType': 'Veuillez entrer le type d\'animal',
          'animalType1': 'Veuillez sélectionner l\'animal',
          'animalRace': 'Veuillez entrer l\'espèce d\'animal de compagnie',

          'animalGender': 'Veuillez entrer le sexe',
          'animalSterilized': 'Votre animal est stérilisé(e)?',
          'animalImage': 'Veuillez télécharger une photo de l\'animal',
          'cameraGallery1': 'Ajouter un Post',
          'chatMedia': 'Sélectionnez le document',
          //friendScreen
          'showLess': 'Afficher moins',
          'showMore': 'Accueil - Forums',
          'suggestions': 'Suggestions',
          'replies': 'Réponses',

          //dialogs(success)
          'deleteComment': 'Votre commentaire a été supprimé.',
          'deletePost': 'Votre post a été supprimé.',
          'report': 'Message signalé avec succès.',
          'animal': 'Votre animal a été ajouté.',
          'noNotification': 'Aucune notification',
          'title': 'Titre',
          'topic': 'Les sujets',
          'favorites': 'Favoris',
          'questionsAsked': 'Question(s) posée(s)',
          'publishedPosts': 'Post(s) publié(s)',
          'atLeastOneCategory': 'Sélectionnez au moins une catégorie',
          'clearFilter': 'Effacer les filtres',

          //dialogs
          'dialogQuestionTitle': 'Supprimer la discussion',
          'dialogQuestion': 'Etes vous sûr de vouloir supprimer la discussion?',
          'dialogCommentTitle': 'Supprimer le commentaire',
          'dialogComment':
              'Êtes-vous sûr de vouloir supprimer le commentaire ?',
          'dialogPostTitle': 'Supprimer le post',
          'dialogPost': 'Êtes-vous sûr de vouloir supprimer le post’ ?',
          'logoutDesc': 'Êtes-vous sûr de vouloir vous déconnecter?',
          'deactivateAccountDesc': 'Voulez-vous vraiment désactiver ce compte?',
          'deleteAccountDesc': 'Voulez-vous vraiment supprimer ce compte ?',
          'newGroup': 'Nouveau groupe chat',
          'skip': 'Passer',

          // reportList
          'doNotLike': 'Je n\'aime tout simplement pas ça',
          'spam': 'C\'est un spam',
          'nudity': 'Nudité ou activité sexuelle',
          'hateSpeech': 'Discours ou symboles de haine',
          'falseInfo': 'Fausse information',
          'groupName': 'Nom du groupe',
          'receiveNotification':
              'Je souhaite recevoir des notifications par e-mail lorsque des commentaires ont été publiés',
          'itching': 'Démangeaisons - Chute de poils',
          'lowIrritation': 'Faible irritation - Poils ternes',
          'everythingIsFine': 'Tout va bien - poils soyeux',
          'myThread': 'Mes discussions',
          'doesLike': 'Refuse de manger',
          'likes': 'Aime sans plus',
          'like': 'Comme',
          'wantsMore': 'En raffole',
          'forums': 'Forums',
          'blockedContact':
              'Vous avez bloqué ce contact. Appuyez pour débloquer',
          'replyBy': 'Répondu par',
          'abnormalPoops': 'Selles anormales',
          'stomach pain or gas': 'Flatulence - maux estomac',
          'everythingFine': 'Tout va bien',
          'offline': 'Hors ligne',
          'online': 'En ligne',
          'brand': 'Marque',
          'fullNameProduct': 'Nom complet du produit',
          'packaging': 'Précision (poids, taille, etc.)',
          'noConversation': 'Aucune conversation',
          'skin': 'Peau ou poils',
          'groupAdmin': 'Admin du groupe',
          'ExitGroup': 'Quitter le groupe',
          'group': 'Groupe',
          'editText': 'Éditer le texte',
          'remove': 'Retirer',
          'areRemove': 'Êtes-vous sûr de vouloir quitter le groupe ?',
          'from': 'depuis',
          'members': 'membre(s)',
          'members1': 'Membre(s)',
          'member': 'membre',
          'groupInfo': 'Informations sur le groupe',
          'changeGroupName': 'Changer le nom du groupe',
          'suggestedForums': 'Les forums 🐶🐱',
          'atLeastOneUser': 'Sélectionnez au moins un utilisateur',
          'enterBrand': 'Veuillez entrer la marque du produit',
          'enterProductName': 'Veuillez entrer le nom du produit',
          'enterPackage': 'Veuillez entrer le poids du produit',
          'noAnimalCreate':
              'Merci d\'ajouter un animal pour pouvoir publier un message',
          'myAnimals': 'Mes animaux',
          'areYouSure': 'Es-tu sûr?',
          'areYouSureDesc': 'Voulez-vous quitter l\'application',
          'dialogReplyTitle': 'Supprimer la réponse',
          'dialogReply': 'Etes-vous sûr de vouloir répondre au commentaire?',
          'deleteReply': 'Votre réponse a été supprimée.',
          //toaster
          'enterEmail': 'Veuillez entrer l\'e-mail',
          'enterPhone': 'Veuillez entrer le numéro de téléphone',
          'enterAddress': 'Veuillez entrer l\'adresse',
          'enterCity': 'Veuillez entrer l\'adresse',

          'validEmail': 'Veuillez entrer votre email valide',
          'enterPassword': 'Veuillez entrer le mot de passe valide',
          'enterPassword1': 'S\'il vous plaît entrer le mot de passe',
          'enterConfirmPassword':
              'Veuillez entrer le mot de passe de confirmation',
          'notMatch': 'Veuillez entrer le mot de passe de confirmation',
          'enterFirstName': 'Veuillez saisir votre prénom',
          'enterLastName': 'Veuillez entrer votre nom de famille',
          'enterDepartment': 'Veuillez entrer votre département',
          'enterPseudo': 'Veuillez entrer un pseudo',
          'currentPassword': 'Veuillez entrer votre mot de passe actuel',
          'cropImage': 'Recadrer l\'image',
          'chooseMembers': 'Choisissez le(s) membre(s)',
          'creategroup': 'Créer une discussion',
          'noReplies': 'Aucune réponse',

          'reviewSubmitted': 'Avis\npublié(s)',
          'questionsSubmitted': 'Question(s)\npubliée(s)',
          'postsSubmitted': 'Discussion(s)\nlancée(s)',
          'responsesSubmitted': 'Réponse(s)\npubliée(s)',

          //notification
          'sendYouMess': "a envoyé un message",
          'hasCommented': 'a commenté ton post',
          'hasReplies': 'a répondu à votre commentaire',
          'hasRepliesTopic': 'a commenté sur votre sujet',
          'likeTopic': "j'ai aimé votre sujet de réponse",
          'startFollow': "a commencé vous suivre",
          'feedLike': 'a liké ton post',

          'year': 'année',
          'years': 'années',
          'month': 'mois',
          'months': 'mois',
          'week': 'semaine',
          'weeks': 'semaines',
          'day': 'jour',
          'days': 'jours',
          'hour': 'heure',
          'hrs': 'heures',
          'min': 'min',
          'justNow': "A l’instant",
          'ago': 'il y a',

          'groupCreated': 'Groupe créé',
          'removed': 'Supprimé',
          'left': 'Gauche',
          'newMember': 'Nouveau membre ajouté',
          'addGroupPhoto': 'Ajouter une photo de groupe',
          'editGroupPhoto': 'modifier une photo de groupe ',
          'more': 'Voir plus',
          'maxPhotos': 'Vous pouvez sélectionner un maximum de 2 images',
          'select2PhotoTitle': 'Ajoutez jusqu\'à 2 photos : ',
          'select2PhotoTitle1': '• une du produit testé',
          'select2PhotoTitle2': '• une de votre animal avec le produit',

          'passcode': "Code d'accès",
        },
      };
}
